project_id = "oipwevcoaugbupicdxqz"

[api]
port = 54331

[db]
port = 54332

[studio]
port = 54333

[inbucket]
port = 54334

[storage]
#port = 54335

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
jwt_secret = "nA7hdP+qhEbBIrlFvrgaqJx1f/W8gXa5PnjQWLNaJLh8sTa6lvAGb4ZdTIsmONxNrhqCf9k8gQFQfivNNd9suA=="
#port = 54336
