

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."badges" (
    "id" integer NOT NULL,
    "challenge_id" integer NOT NULL
);


ALTER TABLE "public"."badges" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."badges_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."badges_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."badges_id_seq" OWNED BY "public"."badges"."id";



CREATE TABLE IF NOT EXISTS "public"."challenge_evaluations" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "deleted_at" timestamp with time zone,
    "succeeded_at" timestamp with time zone,
    "failed_at" timestamp with time zone,
    "errored_at" timestamp with time zone,
    "result" "text",
    "result_text" "text",
    "result_type" character varying,
    "user_challenge_context_id" integer,
    "processed_at" timestamp with time zone,
    "processing_started_at" timestamp with time zone,
    "processor_id" character varying
);


ALTER TABLE "public"."challenge_evaluations" OWNER TO "postgres";


ALTER TABLE "public"."challenge_evaluations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."challenge_evaluation_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."challenges" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "tournament_id" integer NOT NULL,
    "required_tools" "text",
    "evaluation_prompt" "text",
    "system_prompt" "text",
    "initial_llm_prompt" "text"
);


ALTER TABLE "public"."challenges" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."challenges_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."challenges_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."challenges_id_seq" OWNED BY "public"."challenges"."id";



ALTER TABLE "public"."challenges" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."challenges_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tournaments" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "start_date" timestamp with time zone NOT NULL,
    "end_date" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."tournaments" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."tournaments_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."tournaments_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."tournaments_id_seq" OWNED BY "public"."tournaments"."id";



ALTER TABLE "public"."tournaments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tournaments_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_badges" (
    "id" integer NOT NULL,
    "user_id" integer NOT NULL,
    "badge_id" integer NOT NULL,
    "awarded_at" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."user_badges" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."user_badges_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."user_badges_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."user_badges_id_seq" OWNED BY "public"."user_badges"."id";



CREATE TABLE IF NOT EXISTS "public"."user_challenge_context_messages" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_challenge_context_id" integer NOT NULL,
    "content" "text" NOT NULL,
    "content_type" character varying NOT NULL,
    "model" "text",
    "is_user_provided" boolean,
    "role" character varying
);


ALTER TABLE "public"."user_challenge_context_messages" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user_challenge_contexts" (
    "id" integer NOT NULL,
    "can_contribute" boolean NOT NULL,
    "challenge_id" integer NOT NULL,
    "started_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL,
    "last_message_version" bigint DEFAULT '0'::bigint NOT NULL,
    "processing_token" character varying,
    "processing_started_at" timestamp with time zone,
    "last_message_id" bigint
);


ALTER TABLE "public"."user_challenge_contexts" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."user_challenge_contexts_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."user_challenge_contexts_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."user_challenge_contexts_id_seq" OWNED BY "public"."user_challenge_contexts"."id";



ALTER TABLE "public"."user_challenge_context_messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_message_metadata_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_tournament_enrollments" (
    "id" integer NOT NULL,
    "enrolled_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL,
    "tournament_id" integer NOT NULL
);


ALTER TABLE "public"."user_tournament_enrollments" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."user_tournament_enrollments_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."user_tournament_enrollments_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."user_tournament_enrollments_id_seq" OWNED BY "public"."user_tournament_enrollments"."id";



ALTER TABLE "public"."user_tournament_enrollments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_tournament_enrollments_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" integer NOT NULL,
    "sub_id" "text" NOT NULL
);


ALTER TABLE "public"."users" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."users_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."users_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."users_id_seq" OWNED BY "public"."users"."id";



ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."badges" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."badges_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."user_badges" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."user_badges_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."user_challenge_contexts" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."user_challenge_contexts_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."badges"
    ADD CONSTRAINT "badges_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."challenge_evaluations"
    ADD CONSTRAINT "challenge_evaluation_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."challenge_evaluations"
    ADD CONSTRAINT "challenge_evaluation_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."challenges"
    ADD CONSTRAINT "challenges_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."challenges"
    ADD CONSTRAINT "challenges_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tournaments"
    ADD CONSTRAINT "tournaments_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."tournaments"
    ADD CONSTRAINT "tournaments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_badges"
    ADD CONSTRAINT "uq_user_badge" UNIQUE ("user_id", "badge_id");



ALTER TABLE ONLY "public"."user_challenge_contexts"
    ADD CONSTRAINT "uq_user_challenge" UNIQUE ("user_id", "challenge_id");



ALTER TABLE ONLY "public"."user_tournament_enrollments"
    ADD CONSTRAINT "uq_user_tournament" UNIQUE ("user_id", "tournament_id");



ALTER TABLE ONLY "public"."user_badges"
    ADD CONSTRAINT "user_badges_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_challenge_contexts"
    ADD CONSTRAINT "user_challenge_contexts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_challenge_context_messages"
    ADD CONSTRAINT "user_message_metadata_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_tournament_enrollments"
    ADD CONSTRAINT "user_tournament_enrollments_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."user_tournament_enrollments"
    ADD CONSTRAINT "user_tournament_enrollments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_sub_id_key" UNIQUE ("sub_id");



CREATE INDEX "idx_badges_challenge_id" ON "public"."badges" USING "btree" ("challenge_id");



CREATE INDEX "idx_challenges_tournament_id" ON "public"."challenges" USING "btree" ("tournament_id");



CREATE INDEX "idx_contexts_challenge_id" ON "public"."user_challenge_contexts" USING "btree" ("challenge_id");



CREATE INDEX "idx_contexts_user_id" ON "public"."user_challenge_contexts" USING "btree" ("user_id");



CREATE INDEX "idx_enrollments_tournament_id" ON "public"."user_tournament_enrollments" USING "btree" ("tournament_id");



CREATE INDEX "idx_enrollments_user_id" ON "public"."user_tournament_enrollments" USING "btree" ("user_id");



CREATE INDEX "idx_tournaments_dates" ON "public"."tournaments" USING "btree" ("start_date", "end_date");



CREATE INDEX "idx_user_badges_badge_id" ON "public"."user_badges" USING "btree" ("badge_id");



CREATE INDEX "idx_user_badges_user_id" ON "public"."user_badges" USING "btree" ("user_id");



CREATE INDEX "idx_user_message_metadata_created_at" ON "public"."user_challenge_context_messages" USING "btree" ("created_at");



CREATE INDEX "idx_user_message_metadata_user_id" ON "public"."user_challenge_context_messages" USING "btree" ("user_challenge_context_id");



CREATE INDEX "idx_users_sub_id" ON "public"."users" USING "btree" ("sub_id");



ALTER TABLE ONLY "public"."challenge_evaluations"
    ADD CONSTRAINT "challenge_evaluation_user_challenge_context_id_fkey" FOREIGN KEY ("user_challenge_context_id") REFERENCES "public"."user_challenge_contexts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."badges"
    ADD CONSTRAINT "fk_badge_challenge" FOREIGN KEY ("challenge_id") REFERENCES "public"."challenges"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."challenges"
    ADD CONSTRAINT "fk_challenge_tournament" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_challenge_contexts"
    ADD CONSTRAINT "fk_context_challenge" FOREIGN KEY ("challenge_id") REFERENCES "public"."challenges"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_challenge_contexts"
    ADD CONSTRAINT "fk_context_user" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_tournament_enrollments"
    ADD CONSTRAINT "fk_enrollment_tournament" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_tournament_enrollments"
    ADD CONSTRAINT "fk_enrollment_user" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_badges"
    ADD CONSTRAINT "fk_user_badge_badge" FOREIGN KEY ("badge_id") REFERENCES "public"."badges"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_badges"
    ADD CONSTRAINT "fk_user_badge_user" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_challenge_context_messages"
    ADD CONSTRAINT "user_challenge_context_messages_user_challenge_context_id_fkey" FOREIGN KEY ("user_challenge_context_id") REFERENCES "public"."user_challenge_contexts"("id") ON DELETE CASCADE;



ALTER TABLE "public"."badges" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."challenge_evaluations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."challenges" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tournaments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_badges" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_challenge_context_messages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_challenge_contexts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_tournament_enrollments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."badges" TO "anon";
GRANT ALL ON TABLE "public"."badges" TO "authenticated";
GRANT ALL ON TABLE "public"."badges" TO "service_role";



GRANT ALL ON SEQUENCE "public"."badges_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."badges_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."badges_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."challenge_evaluations" TO "anon";
GRANT ALL ON TABLE "public"."challenge_evaluations" TO "authenticated";
GRANT ALL ON TABLE "public"."challenge_evaluations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."challenge_evaluation_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."challenge_evaluation_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."challenge_evaluation_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."challenges" TO "anon";
GRANT ALL ON TABLE "public"."challenges" TO "authenticated";
GRANT ALL ON TABLE "public"."challenges" TO "service_role";



GRANT ALL ON SEQUENCE "public"."challenges_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."challenges_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."challenges_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."challenges_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."challenges_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."challenges_id_seq1" TO "service_role";



GRANT ALL ON TABLE "public"."tournaments" TO "anon";
GRANT ALL ON TABLE "public"."tournaments" TO "authenticated";
GRANT ALL ON TABLE "public"."tournaments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tournaments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tournaments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tournaments_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tournaments_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."tournaments_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tournaments_id_seq1" TO "service_role";



GRANT ALL ON TABLE "public"."user_badges" TO "anon";
GRANT ALL ON TABLE "public"."user_badges" TO "authenticated";
GRANT ALL ON TABLE "public"."user_badges" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_badges_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_badges_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_badges_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_challenge_context_messages" TO "anon";
GRANT ALL ON TABLE "public"."user_challenge_context_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."user_challenge_context_messages" TO "service_role";



GRANT ALL ON TABLE "public"."user_challenge_contexts" TO "anon";
GRANT ALL ON TABLE "public"."user_challenge_contexts" TO "authenticated";
GRANT ALL ON TABLE "public"."user_challenge_contexts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_challenge_contexts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_challenge_contexts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_challenge_contexts_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_message_metadata_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_message_metadata_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_message_metadata_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_tournament_enrollments" TO "anon";
GRANT ALL ON TABLE "public"."user_tournament_enrollments" TO "authenticated";
GRANT ALL ON TABLE "public"."user_tournament_enrollments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_tournament_enrollments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_tournament_enrollments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_tournament_enrollments_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_tournament_enrollments_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_tournament_enrollments_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_tournament_enrollments_id_seq1" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq1" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;
